# Generated by Django 2.1.1 on 2018-10-01 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_priority',
            field=models.CharField(choices=[('high', 'HIGH'), ('medium', 'MEDIUM'), ('low', 'LOW')], default='LOW', max_length=10),
        ),
    ]
